### ISSUE TITLE
Excellent demo and a nitpick

### ISSUE THREAD

**Issue by cf250024** [alexmt/argo-combined-demo#2]
It took me some time to figure out that uploaded images have to be with suffix ".jpg" as in filter in event source to trigger the workflow. Can you put that in README.md or expand the filter?

Also I have metallb as load balancer and it works for argo-cd with https://172.42.42.10.244. I can see all the apps synced with green color.

But for argo-server http://172.42.42.241 and filestash http://172.42.42.243 they aren't working. I have to use  node port for them to work. Not sure why?
<img width="1644" alt="Screen Shot 2020-12-14 at 7 39 00 PM" src="https://user-images.githubusercontent.com/59401847/102168139-9432fd80-3e44-11eb-84c8-815a8e3d14f3.png">

At the end of the day, the basic flow is working. Thanks for the demo.

**Comment by alexmt** [comment]
Thank you @cf250024 ! Added (https://github.com/alexmt/kubecon-2020-demo/commit/ea5b3f191cd8b3bafef2639924d837e88d00ed95) a note about .jpg file extension. The argo-server and filestash are available on ports `2746` and `9001`. Mentioned (https://github.com/alexmt/kubecon-2020-demo/commit/ea5b3f191cd8b3bafef2639924d837e88d00ed95) ports in README.md as well.
